-- Development seed data
-- This file is NOT a migration. It only runs locally via:
--   npx supabase db reset
--
-- It will NOT run in production.
--
-- NOTE: Exercise data is now imported via YAML files.
-- After running 'pnpm db:reset', run:
--   pnpm db:import-exercises
--
-- YAML files location: exercises/python/*.yaml

-- No seed data here - exercises come from YAML import
-- This file is kept to document the workflow
