// src/lib/paths/client-loader.ts
//
// Client-safe path index loader that uses pre-generated JSON.
// This avoids Node.js fs dependencies that can't run in the browser.
//
// The JSON is generated by: pnpm generate:paths

import type { Blueprint, Skin, PathIndex, BlueprintRef } from './types';

// Import the pre-generated JSON
// This file is created by scripts/generate-path-index.ts
import generatedIndex from './generated/path-index.json';

interface SerializedPathIndex {
  blueprints: Record<string, Blueprint>;
  skins: Record<string, Skin>;
  exerciseToBlueprints: Record<string, BlueprintRef[]>;
  exerciseToSkins: Record<string, string[]>;
}

// Type assertion for the imported JSON
const serializedIndex = generatedIndex as SerializedPathIndex;

// Convert serialized index (objects) to PathIndex (Maps) - cached
let cachedPathIndex: PathIndex | null = null;

function deserializeIndex(serialized: SerializedPathIndex): PathIndex {
  return {
    blueprints: new Map(Object.entries(serialized.blueprints)),
    skins: new Map(Object.entries(serialized.skins)),
    exerciseToBlueprints: new Map(Object.entries(serialized.exerciseToBlueprints)),
    exerciseToSkins: new Map(Object.entries(serialized.exerciseToSkins)),
  };
}

/**
 * Get the path index (client-safe, synchronous).
 * Uses pre-generated JSON data.
 */
export function getPathIndexSync(): PathIndex {
  if (!cachedPathIndex) {
    cachedPathIndex = deserializeIndex(serializedIndex);
  }
  return cachedPathIndex;
}

/**
 * Get the path index (async version for API compatibility).
 * Returns immediately since data is pre-loaded.
 */
export async function getPathIndex(): Promise<PathIndex> {
  return getPathIndexSync();
}

/**
 * Clear the cached index (useful for testing)
 */
export function clearPathIndexCache(): void {
  cachedPathIndex = null;
}
